runtime: python39
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main_prod:app
instance_class: F2

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: static/favicon\.ico

  - url: /
    static_files: index.html
    upload: static/index\.html

  - url: /static
    static_dir: static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
