[tool.vulture]
min_confidence = 61

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.mypy]
python_version = 3.9
#disallow_any_unimported = true
#disallow_any_explicit = true
#disallow_subclassing_any = true
#disallow_untyped_calls = true
#disallow_untyped_defs = true
#disallow_incomplete_defs = true
#check_untyped_defs = true
#no_implicit_optional = true
#warn_redundant_casts = true
#warn_unused_ignores = true
#warn_return_any = true